language: python

branches:
 only:
  - master
  - dev/travis

matrix:
 include:
  - python: 3.4
    env: TOXENV=py34-core

  - python: 3.5
    env: TOXENV=py35-core

install:
 - pip install tox

script:
 - tox
